# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.6.3
_src_path: gh:algorandfoundation/algokit-python-template
author_email: TUF15xveili@protonmail.com
author_name: jizen
contract_name: salvo
deployment_language: python
preset_name: production
project_name: Salvo-contracts

