# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.6
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: TUF15xveili@protonmail.com
author_name: jizen
cloud_provider: none
contract_name: salvo
deployment_language: python
preset_name: production
project_name: Salvo

